# Generated by Django 4.2.7 on 2025-08-26 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_task'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='task',
            new_name='task_created_18c8cb_idx',
            old_name='app01_task_created__da85e8_idx',
        ),
    ]
