# Generated by Django 4.2.7 on 2025-08-28 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_rename_app01_task_created__da85e8_idx_task_created_18c8cb_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=20, verbose_name='原状态')),
                ('to_status', models.CharField(max_length=20, verbose_name='新状态')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='变更时间')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='变更原因')),
            ],
            options={
                'verbose_name': '任务状态日志',
                'verbose_name_plural': '任务状态日志',
                'db_table': 'task_status_log',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('approved', '已通过'), ('scheduled', '已排程'), ('in_progress', '进行中'), ('completed', '已完成'), ('rejected', '已驳回'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='task_status_e9a322_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_at'], name='task_created_fe28b4_idx'),
        ),
        migrations.AddField(
            model_name='taskstatuslog',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='变更人'),
        ),
        migrations.AddField(
            model_name='taskstatuslog',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='app01.task', verbose_name='任务'),
        ),
        migrations.AddIndex(
            model_name='taskstatuslog',
            index=models.Index(fields=['task', 'changed_at'], name='task_status_task_id_59d29b_idx'),
        ),
        migrations.AddIndex(
            model_name='taskstatuslog',
            index=models.Index(fields=['changed_by', 'changed_at'], name='task_status_changed_5cc382_idx'),
        ),
    ]
