# Generated by Django 4.2.7 on 2025-08-28 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_migrate_task_statuses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='source',
        ),
    ]
