# Generated by Django 4.2.23 on 2025-09-07 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_remove_source_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='唯一名')),
                ('state', models.CharField(choices=[('idle', '空闲'), ('in_use', '使用中')], default='idle', max_length=16, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '转移仓',
                'verbose_name_plural': '转移仓',
                'db_table': 'container',
            },
        ),
        migrations.CreateModel(
            name='ContainerSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='类型名')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='类型编码')),
                ('capacity', models.PositiveIntegerField(verbose_name='容量/槽位数')),
                ('allowed_material_kind', models.CharField(choices=[('test_tube_15', '15mL试管'), ('laiyu_powder', '铼羽粉筒'), ('jingtai_powder', '晶泰粉筒'), ('reagent_bottle_150', '150mL试剂瓶'), ('tip_1', '1mL枪头'), ('tip_5', '5mL枪头'), ('tip_10', '10mL枪头'), ('sample_filter', '采样滤头'), ('filtration_filter', '过滤滤头'), ('mixture_tube', '混合瓶'), ('sample_tube', '采样瓶'), ('sample_cylinder', '进样柱'), ('chromatographic_cylinder', '色谱柱')], max_length=64, verbose_name='允许物料类型')),
                ('slot_meta_schema', models.JSONField(blank=True, null=True, verbose_name='槽位Meta结构定义')),
            ],
            options={
                'verbose_name': '转移仓类型规范',
                'verbose_name_plural': '转移仓类型规范',
                'db_table': 'container_spec',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='工站名')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '工站',
                'verbose_name_plural': '工站',
                'db_table': 'station',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', '管理员'), ('preparator', '备料员'), ('user', '普通用户')], default='user', max_length=10, verbose_name='用户角色'),
        ),
        migrations.CreateModel(
            name='TestTube15',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='唯一名')),
                ('state', models.CharField(choices=[('idle', '空闲'), ('in_use', '使用中')], default='idle', max_length=16, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('current_container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.container', verbose_name='当前转移仓')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.task', verbose_name='实验任务ID')),
            ],
            options={
                'verbose_name': '15mL试管',
                'verbose_name_plural': '15mL试管',
                'db_table': 'test_tube_15',
            },
        ),
        migrations.CreateModel(
            name='ReagentBottle150',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='唯一名')),
                ('reagent_name', models.CharField(max_length=128, verbose_name='试剂名称')),
                ('volume_ml', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='体积(mL)')),
                ('state', models.CharField(choices=[('idle', '空闲'), ('in_use', '使用中')], default='idle', max_length=16, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('current_container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.container', verbose_name='当前转移仓')),
            ],
            options={
                'verbose_name': '150mL试剂瓶',
                'verbose_name_plural': '150mL试剂瓶',
                'db_table': 'reagent_bottle_150',
            },
        ),
        migrations.CreateModel(
            name='LaiyuPowder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='唯一名')),
                ('material_name', models.CharField(max_length=128, verbose_name='粉末名称')),
                ('mass_mg', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='质量(mg)')),
                ('state', models.CharField(choices=[('idle', '空闲'), ('in_use', '使用中')], default='idle', max_length=16, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('current_container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.container', verbose_name='当前转移仓')),
            ],
            options={
                'verbose_name': '铼羽粉筒',
                'verbose_name_plural': '铼羽粉筒',
                'db_table': 'laiyu_powder',
            },
        ),
        migrations.CreateModel(
            name='JingtaiPowder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='唯一名')),
                ('material_name', models.CharField(max_length=128, verbose_name='粉末名称')),
                ('mass_mg', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='质量(mg)')),
                ('state', models.CharField(choices=[('idle', '空闲'), ('in_use', '使用中')], default='idle', max_length=16, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('current_container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.container', verbose_name='当前转移仓')),
            ],
            options={
                'verbose_name': '晶泰粉筒',
                'verbose_name_plural': '晶泰粉筒',
                'db_table': 'jingtai_powder',
            },
        ),
        migrations.AddField(
            model_name='container',
            name='current_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.station', verbose_name='当前工站'),
        ),
        migrations.AddField(
            model_name='container',
            name='spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='containers', to='app01.containerspec', verbose_name='类型'),
        ),
        migrations.CreateModel(
            name='ContainerSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(verbose_name='槽位编号(0-based)')),
                ('meta', models.JSONField(blank=True, null=True, verbose_name='槽位元数据')),
                ('occupied', models.BooleanField(default=False, verbose_name='是否占用')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='app01.container', verbose_name='转移仓')),
                ('jingtai_powder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.jingtaipowder')),
                ('laiyu_powder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.laiyupowder')),
                ('reagent_bottle_150', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.reagentbottle150')),
                ('test_tube_15', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.testtube15')),
            ],
            options={
                'verbose_name': '转移仓槽位',
                'verbose_name_plural': '转移仓槽位',
                'db_table': 'container_slot',
                'indexes': [models.Index(fields=['container', 'index'], name='container_s_contain_812376_idx'), models.Index(fields=['occupied'], name='container_s_occupie_b121be_idx')],
                'unique_together': {('container', 'index')},
            },
        ),
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['spec', 'state'], name='container_spec_id_3b8715_idx'),
        ),
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['current_station', 'state'], name='container_current_9561a3_idx'),
        ),
    ]
