# Generated by Django 4.2.7 on 2025-09-09 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_container_containerspec_station_alter_user_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreparationList',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='清单ID')),
                ('task_ids', models.JSONField(verbose_name='任务ID列表')),
                ('materials_required', models.JSONField(verbose_name='物料需求')),
                ('containers_required', models.JSONField(verbose_name='转移仓需求')),
                ('reagents_info', models.JSONField(verbose_name='试剂信息')),
                ('status', models.CharField(choices=[('pending', '待备料'), ('in_progress', '备料中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '备料清单',
                'verbose_name_plural': '备料清单',
                'db_table': 'preparation_list',
            },
        ),
        migrations.CreateModel(
            name='FillOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_index', models.PositiveIntegerField(verbose_name='槽位索引')),
                ('material_id', models.PositiveIntegerField(verbose_name='物料ID')),
                ('material_kind', models.CharField(max_length=64, verbose_name='物料类型')),
                ('material_name', models.CharField(max_length=128, verbose_name='物料名称')),
                ('operated_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.container', verbose_name='转移仓')),
                ('operated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('preparation_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='app01.preparationlist', verbose_name='备料清单')),
            ],
            options={
                'verbose_name': '装填操作',
                'verbose_name_plural': '装填操作',
                'db_table': 'fill_operation',
                'ordering': ['-operated_at'],
            },
        ),
    ]
