# Generated by Django 4.2.23 on 2025-09-13 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_preparationlist_filloperation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preparationlist',
            options={'ordering': ['-created_at'], 'verbose_name': '备料清单', 'verbose_name_plural': '备料清单'},
        ),
        migrations.RemoveField(
            model_name='preparationlist',
            name='containers_required',
        ),
        migrations.RemoveField(
            model_name='preparationlist',
            name='materials_required',
        ),
        migrations.RemoveField(
            model_name='preparationlist',
            name='reagents_info',
        ),
        migrations.AddField(
            model_name='preparationlist',
            name='station_materials',
            field=models.JSONField(default=dict, help_text='按工站分组的物料需求统计', verbose_name='按工站物料需求'),
        ),
        migrations.AddField(
            model_name='preparationlist',
            name='station_reagents',
            field=models.JSONField(default=dict, help_text='按工站分组的试剂信息', verbose_name='按工站试剂信息'),
        ),
        migrations.AddField(
            model_name='station',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='station',
            name='station_type',
            field=models.CharField(choices=[('manual_prep', '人工备料'), ('solid_liquid', '固液配料'), ('reaction', '反应'), ('glovebox', '手套箱固液配料与反应'), ('filtration', '过滤分液'), ('evaporation', '旋蒸'), ('column', '过柱'), ('tlc', '点板'), ('gcms', 'GCMS'), ('hplc', 'HPLC')], default='manual_prep', max_length=32, verbose_name='工站类型'),
        ),
    ]
