# Generated by Django 4.2.23 on 2025-09-13 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_alter_preparationlist_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preparationlist',
            name='station_reagents',
        ),
    ]
