# Generated by Django 4.2.23 on 2025-09-14 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_remove_station_reagents_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparationlist',
            name='material_fill_bindings',
            field=models.JSONField(default=dict, help_text='记录备料清单中物料需求与实际装填物料的绑定关系，结构：{工站: {物料类型: {索引: 绑定信息}}}', verbose_name='物料装填绑定关系'),
        ),
    ]
