# Generated by Django 4.2.23 on 2025-09-14 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_preparationlist_material_fill_bindings'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='target_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_containers', to='app01.station', verbose_name='目标工站'),
        ),
        migrations.AlterField(
            model_name='container',
            name='current_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_containers', to='app01.station', verbose_name='当前工站'),
        ),
    ]
