# Generated by Django 4.2.23 on 2025-09-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_container_target_station_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filloperation',
            name='material_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='物料ID'),
        ),
    ]
