# Generated by Django 4.2.23 on 2025-09-14 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_alter_filloperation_material_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreparationStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('prep_1', '备料区-1'), ('prep_2', '备料区-2'), ('prep_3', '备料区-3'), ('prep_4', '备料区-4'), ('prep_5', '备料区-5'), ('prep_6', '备料区-6'), ('prep_7', '备料区-7'), ('prep_8', '备料区-8'), ('prep_9', '备料区-9'), ('prep_10', '备料区-10'), ('prep_11', '备料区-11'), ('prep_12', '备料区-12'), ('return_1', '回料区-1'), ('return_2', '回料区-2'), ('return_3', '回料区-3'), ('return_4', '回料区-4'), ('return_5', '回料区-5'), ('return_6', '回料区-6'), ('return_7', '回料区-7'), ('return_8', '回料区-8'), ('return_9', '回料区-9'), ('return_10', '回料区-10'), ('return_11', '回料区-11'), ('return_12', '回料区-12')], max_length=20, unique=True, verbose_name='位置')),
                ('area_type', models.CharField(choices=[('preparation', '备料区'), ('return', '回料区')], max_length=20, verbose_name='区域类型')),
                ('position_name', models.CharField(max_length=100, verbose_name='位置名称')),
                ('expected_material_kind', models.CharField(choices=[('test_tube_15', '15mL试管'), ('laiyu_powder', '铼羽粉筒'), ('jingtai_powder', '晶泰粉筒'), ('reagent_bottle_150', '150mL试剂瓶'), ('tip_1', '1mL枪头'), ('tip_5', '5mL枪头'), ('tip_10', '10mL枪头'), ('sample_filter', '采样滤头'), ('filtration_filter', '过滤滤头'), ('mixture_tube', '混合瓶'), ('sample_tube', '采样瓶'), ('sample_cylinder', '进样柱'), ('chromatographic_cylinder', '色谱柱')], max_length=64, verbose_name='预期物料类型')),
                ('is_occupied', models.BooleanField(default=False, verbose_name='是否被占用')),
                ('placed_at', models.DateTimeField(blank=True, null=True, verbose_name='放置时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('current_container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.container', verbose_name='当前转移仓')),
                ('placed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='放置人')),
            ],
            options={
                'verbose_name': '备料工站位置',
                'verbose_name_plural': '备料工站位置',
                'db_table': 'preparation_station',
                'ordering': ['area_type', 'position'],
                'indexes': [models.Index(fields=['area_type', 'position'], name='preparation_area_ty_3ebc5a_idx'), models.Index(fields=['is_occupied'], name='preparation_is_occu_7c4dea_idx')],
            },
        ),
    ]
