# Generated by Django 4.2.7 on 2025-09-25 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_datafile_mlalgorithm_mltask_mltaskresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing_type', models.CharField(choices=[('missing_values', '缺失值处理'), ('outliers', '异常值处理'), ('data_split', '数据分割')], max_length=20, verbose_name='处理类型')),
                ('parameters', models.JSONField(verbose_name='处理参数')),
                ('result_summary', models.TextField(blank=True, verbose_name='处理结果摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('data_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.datafile', verbose_name='数据文件')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '数据处理日志',
                'verbose_name_plural': '数据处理日志',
                'db_table': 'data_processing_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
