# Generated by Django 4.2.7 on 2025-09-25 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0016_dataprocessinglog'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='data_types',
            field=models.JSONField(blank=True, null=True, verbose_name='数据类型'),
        ),
        migrations.AddField(
            model_name='datafile',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='错误信息'),
        ),
        migrations.AddField(
            model_name='datafile',
            name='missing_values',
            field=models.JSONField(blank=True, null=True, verbose_name='缺失值统计'),
        ),
        migrations.AddField(
            model_name='datafile',
            name='outlier_info',
            field=models.JSONField(blank=True, null=True, verbose_name='异常值统计'),
        ),
        migrations.AddField(
            model_name='datafile',
            name='processing_log',
            field=models.TextField(blank=True, verbose_name='处理日志'),
        ),
    ]
