# Generated by Django 4.2.7 on 2025-09-25 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0017_datafile_data_types_datafile_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataprocessinglog',
            name='processing_log',
            field=models.TextField(blank=True, verbose_name='处理日志'),
        ),
    ]
