# Generated by Django 4.2.7 on 2025-09-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0018_dataprocessinglog_processing_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlalgorithm',
            name='default_parameters',
            field=models.JSONField(default=dict, verbose_name='默认参数(兼容)'),
        ),
        migrations.AddField(
            model_name='mlalgorithm',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='是否付费算法'),
        ),
        migrations.AddField(
            model_name='mlalgorithm',
            name='parameter_schema',
            field=models.JSONField(default=dict, verbose_name='参数配置模式(兼容)'),
        ),
        migrations.AlterField(
            model_name='mlalgorithm',
            name='parameters_schema',
            field=models.JSONField(default=dict, verbose_name='参数配置模式'),
        ),
    ]
