# Generated by Django 4.2.7 on 2025-09-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0019_mlalgorithm_default_parameters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mltask',
            name='feature_columns',
            field=models.JSONField(blank=True, null=True, verbose_name='特征列列表'),
        ),
        migrations.AddField(
            model_name='mltask',
            name='target_column',
            field=models.CharField(blank=True, max_length=255, verbose_name='目标列'),
        ),
        migrations.AddField(
            model_name='mltask',
            name='test_ratio',
            field=models.FloatField(default=0.2, verbose_name='测试集比例'),
        ),
        migrations.AddField(
            model_name='mltask',
            name='train_ratio',
            field=models.FloatField(default=0.8, verbose_name='训练集比例'),
        ),
        migrations.AddField(
            model_name='mltask',
            name='training_log',
            field=models.TextField(blank=True, verbose_name='训练日志'),
        ),
        migrations.AddField(
            model_name='mltask',
            name='validation_ratio',
            field=models.FloatField(default=0.0, verbose_name='验证集比例'),
        ),
    ]
