# Generated by Django 4.2.7 on 2025-09-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0020_mltask_feature_columns_mltask_target_column_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mltaskresult',
            name='chart_data',
            field=models.JSONField(blank=True, null=True, verbose_name='图表数据'),
        ),
        migrations.AddField(
            model_name='mltaskresult',
            name='confusion_matrix',
            field=models.JSONField(blank=True, null=True, verbose_name='混淆矩阵'),
        ),
        migrations.AddField(
            model_name='mltaskresult',
            name='feature_importance',
            field=models.JSONField(blank=True, null=True, verbose_name='特征重要性'),
        ),
        migrations.AddField(
            model_name='mltaskresult',
            name='learning_curve',
            field=models.JSONField(blank=True, null=True, verbose_name='学习曲线'),
        ),
        migrations.AddField(
            model_name='mltaskresult',
            name='mae',
            field=models.FloatField(blank=True, null=True, verbose_name='平均绝对误差'),
        ),
    ]
