# Generated by Django 4.2.7 on 2025-10-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0022_reagent_reagentspectrum_reagentoperation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reagentspectrum',
            name='binary_content',
            field=models.BinaryField(blank=True, null=True, verbose_name='二进制内容'),
        ),
        migrations.AddField(
            model_name='reagentspectrum',
            name='content_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='内容类型'),
        ),
        migrations.AddField(
            model_name='reagentspectrum',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='文件大小(字节)'),
        ),
        migrations.AddField(
            model_name='reagentspectrum',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='原始文件名'),
        ),
        migrations.AlterField(
            model_name='reagentspectrum',
            name='file_path',
            field=models.CharField(blank=True, max_length=500, verbose_name='文件路径'),
        ),
    ]
