# Generated by Django 4.1.13 on 2025-10-09 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0023_reagentspectrum_binary_content_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BayesianOptTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_name",
                    models.CharField(max_length=200, verbose_name="任务名称"),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[("reaction", "化学反应优化"), ("general", "通用优化")],
                        default="reaction",
                        max_length=50,
                        verbose_name="任务类型",
                    ),
                ),
                (
                    "objective_name",
                    models.CharField(max_length=100, verbose_name="优化目标名称"),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("maximize", "最大化"), ("minimize", "最小化")],
                        default="maximize",
                        max_length=10,
                        verbose_name="优化方向",
                    ),
                ),
                (
                    "per_round_suggest",
                    models.IntegerField(default=3, verbose_name="每轮推荐数量"),
                ),
                (
                    "parameter_space",
                    models.JSONField(default=dict, verbose_name="参数空间"),
                ),
                (
                    "current_round",
                    models.IntegerField(default=0, verbose_name="当前轮次"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否活跃"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bo_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建用户",
                    ),
                ),
                (
                    "data_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app01.datafile",
                        verbose_name="历史CSV数据",
                    ),
                ),
            ],
            options={
                "verbose_name": "贝叶斯优化任务",
                "verbose_name_plural": "贝叶斯优化任务",
                "db_table": "bo_task",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="BOIteration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_index", models.IntegerField(verbose_name="轮次(从1开始)")),
                (
                    "suggestions",
                    models.JSONField(default=list, verbose_name="推荐参数集合"),
                ),
                (
                    "best_objective",
                    models.FloatField(
                        blank=True, null=True, verbose_name="截至本轮最优目标值"
                    ),
                ),
                (
                    "best_params",
                    models.JSONField(
                        blank=True, null=True, verbose_name="截至本轮对应参数"
                    ),
                ),
                (
                    "scatter_chart",
                    models.JSONField(
                        blank=True, null=True, verbose_name="散点图数据缓存"
                    ),
                ),
                (
                    "convergence_chart",
                    models.JSONField(
                        blank=True, null=True, verbose_name="收敛曲线数据缓存"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="iterations",
                        to="app01.bayesianopttask",
                        verbose_name="所属任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "贝叶斯优化轮次",
                "verbose_name_plural": "贝叶斯优化轮次",
                "db_table": "bo_iteration",
                "ordering": ["task_id", "round_index"],
            },
        ),
        migrations.CreateModel(
            name="BOTrial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("params", models.JSONField(default=dict, verbose_name="参数")),
                (
                    "objective",
                    models.FloatField(blank=True, null=True, verbose_name="目标值"),
                ),
                (
                    "source_row",
                    models.JSONField(blank=True, null=True, verbose_name="原始数据行"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "iteration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trials",
                        to="app01.boiteration",
                        verbose_name="所属轮次",
                    ),
                ),
            ],
            options={
                "verbose_name": "贝叶斯优化实验点",
                "verbose_name_plural": "贝叶斯优化实验点",
                "db_table": "bo_trial",
            },
        ),
        migrations.AddIndex(
            model_name="botrial",
            index=models.Index(
                fields=["iteration"], name="bo_trial_iterati_f7ce86_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="boiteration",
            unique_together={("task", "round_index")},
        ),
        migrations.AddIndex(
            model_name="bayesianopttask",
            index=models.Index(
                fields=["created_by", "updated_at"], name="bo_task_created_3831cf_idx"
            ),
        ),
    ]
