# Generated by Django 4.2.25 on 2025-10-23 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0024_bayesianopttask_boiteration_botrial_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GcmsTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bottle_num", models.IntegerField(verbose_name="样品瓶号")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待运行"),
                            ("running", "运行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gcms_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "GCMS分析任务",
                "verbose_name_plural": "GCMS分析任务",
                "db_table": "gcms_task",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status"], name="gcms_task_status_ddb119_idx"),
                    models.Index(
                        fields=["created_by"], name="gcms_task_created_828070_idx"
                    ),
                ],
            },
        ),
    ]
