# Generated by Django 5.2.5 on 2025-11-04 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0024_bayesianopttask_boiteration_botrial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='current_position',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='当前位置ID'),
        ),
    ]
