# Generated by Django 4.2.25 on 2025-10-27 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0025_gcmstask"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GcmsTask",
        ),
    ]
