# Generated by Django 5.2.5 on 2025-11-06 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0025_container_current_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchingStationPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_id', models.CharField(max_length=32, unique=True, verbose_name='位置ID(如 prep_1)')),
                ('display_name', models.CharField(help_text='例如 位置 1', max_length=64, verbose_name='显示名称')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='显示排序')),
                ('is_occupied', models.BooleanField(default=False, verbose_name='是否被占用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('current_container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.container', verbose_name='当前转移仓')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batching_positions', to='app01.station', verbose_name='所属工站')),
            ],
            options={
                'verbose_name': '固液配料工站位置',
                'verbose_name_plural': '固液配料工站位置',
                'db_table': 'batching_station_position',
                'ordering': ['order_index', 'position_id'],
                'indexes': [models.Index(fields=['station', 'position_id'], name='batching_st_station_df72dd_idx'), models.Index(fields=['is_occupied'], name='batching_st_is_occu_683ba2_idx')],
            },
        ),
    ]
