# Generated by Django 5.2.5 on 2025-11-12 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0026_batchingstationposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255, verbose_name='实验名称')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('approved', '已通过'), ('scheduled', '已排程'), ('in_progress', '进行中'), ('completed', '已完成'), ('rejected', '已驳回'), ('cancelled', '已取消')], max_length=20, verbose_name='状态')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('stations', models.JSONField(blank=True, null=True, verbose_name='工站参数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='写入时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='experiment_detail', to='app01.task', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '实验详情',
                'verbose_name_plural': '实验详情',
                'db_table': '实验详情',
                'indexes': [models.Index(fields=['created_by', 'created_at'], name='实验详情_created_30e259_idx'), models.Index(fields=['status'], name='实验详情_status_2b40fa_idx')],
            },
        ),
    ]
