# Generated by Django 4.2.25 on 2025-11-18 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0026_delete_gcmstask"),
    ]

    operations = [
        migrations.CreateModel(
            name="HPLCTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_id", models.IntegerField(verbose_name="展示ID(用户内自增)")),
                (
                    "experiment_name",
                    models.CharField(max_length=255, verbose_name="实验名称"),
                ),
                ("bottle_num", models.IntegerField(verbose_name="样品瓶号")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待运行"),
                            ("queued", "排队中"),
                            ("task_started", "任务开始"),
                            ("device_preparation", "设备准备"),
                            ("arm_operation", "机械臂操作"),
                            ("instrument_analysis", "仪器分析"),
                            ("waiting_completion", "等待分析完成"),
                            ("device_reset", "设备复位"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=32,
                        verbose_name="状态",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(blank=True, null=True, verbose_name="用时(秒)"),
                ),
                (
                    "archive_id",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="归档ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "HPLC任务",
                "verbose_name_plural": "HPLC任务",
                "db_table": "hplc_task",
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["created_by", "created_at"],
                        name="hplc_task_created_564ad7_idx",
                    ),
                    models.Index(fields=["status"], name="hplc_task_status_fcc1dc_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="GCMSTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_id", models.IntegerField(verbose_name="展示ID(用户内自增)")),
                (
                    "experiment_name",
                    models.CharField(max_length=255, verbose_name="实验名称"),
                ),
                ("bottle_num", models.IntegerField(verbose_name="样品瓶号")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待运行"),
                            ("queued", "排队中"),
                            ("task_started", "任务开始"),
                            ("device_preparation", "设备准备"),
                            ("arm_operation", "机械臂操作"),
                            ("instrument_analysis", "仪器分析"),
                            ("waiting_completion", "等待分析完成"),
                            ("device_reset", "设备复位"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=32,
                        verbose_name="状态",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(blank=True, null=True, verbose_name="用时(秒)"),
                ),
                (
                    "archive_id",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="归档ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("sequence_index", models.IntegerField(verbose_name="序列号")),
                (
                    "sequence_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="序列文件名"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "GCMS任务",
                "verbose_name_plural": "GCMS任务",
                "db_table": "gcms_task",
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["created_by", "created_at"],
                        name="gcms_task_created_3c5b46_idx",
                    ),
                    models.Index(fields=["status"], name="gcms_task_status_ddb119_idx"),
                ],
            },
        ),
    ]
