# Generated by Django 5.2.5 on 2025-11-13 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0027_experimentdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactionStirrer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='设备编号(1-20)')),
                ('name', models.CharField(default='磁搅', max_length=64, verbose_name='名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('online_status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('unknown', '未知')], default='unknown', max_length=10, verbose_name='在线状态')),
                ('current_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='当前温度(°C)')),
                ('target_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='目标温度(°C)')),
                ('stirring_speed', models.PositiveIntegerField(blank=True, null=True, verbose_name='搅拌速度(rpm)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reaction_stirrers', to='app01.station', verbose_name='所属工站')),
            ],
            options={
                'verbose_name': '反应磁搅',
                'verbose_name_plural': '反应磁搅',
                'db_table': 'reaction_stirrer',
                'ordering': ['station_id', 'number'],
            },
        ),
        migrations.CreateModel(
            name='ReactionStirrerHole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole_index', models.PositiveIntegerField(verbose_name='孔位(1-12)')),
                ('status', models.CharField(choices=[('idle', '空闲'), ('reacting', '反应中'), ('completed', '已完成')], default='idle', max_length=16, verbose_name='状态')),
                ('setpoints', models.JSONField(blank=True, null=True, verbose_name='设定参数')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('current_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.task', verbose_name='任务')),
                ('stirrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holes', to='app01.reactionstirrer', verbose_name='磁搅设备')),
                ('test_tube', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.testtube15', verbose_name='试管')),
            ],
            options={
                'verbose_name': '反应磁搅孔位',
                'verbose_name_plural': '反应磁搅孔位',
                'db_table': 'reaction_stirrer_hole',
                'ordering': ['stirrer_id', 'hole_index'],
            },
        ),
        migrations.AddIndex(
            model_name='reactionstirrer',
            index=models.Index(fields=['station', 'number'], name='reaction_st_station_1c1cbe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reactionstirrer',
            unique_together={('station', 'number')},
        ),
        migrations.AddIndex(
            model_name='reactionstirrerhole',
            index=models.Index(fields=['stirrer', 'hole_index'], name='reaction_st_stirrer_d37d7a_idx'),
        ),
        migrations.AddIndex(
            model_name='reactionstirrerhole',
            index=models.Index(fields=['status'], name='reaction_st_status_90fff5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reactionstirrerhole',
            unique_together={('stirrer', 'hole_index')},
        ),
    ]
