# Generated by Django 4.2.7 on 2025-11-29 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0027_hplctask_gcmstask'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('deepseek', 'DeepSeek'), ('kimi', 'Kimi'), ('other', 'Other')], max_length=50, verbose_name='模型提供商')),
                ('api_key', models.CharField(max_length=255, verbose_name='API Key')),
                ('model_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='模型名称')),
                ('base_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Base URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'AI模型配置',
                'verbose_name_plural': 'AI模型配置',
                'db_table': 'ai_model_config',
                'unique_together': {('user', 'provider')},
            },
        ),
    ]
