# Generated by Django 5.2.5 on 2025-11-13 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0028_reactionstirrer_reactionstirrerhole_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactionStationPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_id', models.CharField(choices=[('PREP_1', '位置 1'), ('PREP_2', '位置 2'), ('PREP_3', '位置 3'), ('PREP_4', '位置 4'), ('PREP_5', '位置 5'), ('PREP_6', '位置 6'), ('PREP_7', '位置 7'), ('PREP_8', '位置 8'), ('PREP_9', '位置 9'), ('PREP_10', '位置 10'), ('PREP_11', '位置 11'), ('PREP_12', '位置 12')], max_length=32, verbose_name='位置ID(如 PREP_1)')),
                ('display_name', models.CharField(help_text='例如 位置 1', max_length=64, verbose_name='显示名称')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='显示排序')),
                ('is_occupied', models.BooleanField(default=False, verbose_name='是否被占用')),
                ('placed_at', models.DateTimeField(blank=True, null=True, verbose_name='放置时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('current_container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.container', verbose_name='当前转移仓')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reaction_positions', to='app01.station', verbose_name='所属工站')),
            ],
            options={
                'verbose_name': '反应工站位置',
                'verbose_name_plural': '反应工站位置',
                'db_table': 'reaction_station_position',
                'ordering': ['order_index', 'position_id'],
                'indexes': [models.Index(fields=['station', 'position_id'], name='reaction_st_station_bbd757_idx'), models.Index(fields=['is_occupied'], name='reaction_st_is_occu_1950e3_idx')],
                'unique_together': {('station', 'position_id')},
            },
        ),
    ]
